#!/bin/bash

IGNORE_OVERRIDE=0
OVERRIDE=''

if [ "$1" == "-i" ]; then
  IGNORE_OVERRIDE=1
  shift
fi

if [ "$1" == "-o" ]; then
  IGNORE_OVERRIDE=1
  shift
  OVERRIDE="-f ${1}"
  shift
fi

if git rev-parse --is-inside-work-tree 2>&1 > /dev/null; then
  echo "Generate git related environment variables:"
  GIT_VERSION=$(git describe --always)
  GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
  GIT_LASTCOMMITDATE=$(git log -1 --format=%cI)
  GIT_COMMITHASH=$(git rev-parse HEAD)
  printf "%-20s: %s\n" "GIT_VERSION" "${GIT_VERSION}"
  printf "%-20s: %s\n" "GIT_BRANCH" "${GIT_BRANCH}"
  printf "%-20s: %s\n" "GIT_LASTCOMMITDATE" "${GIT_LASTCOMMITDATE}"
  printf "%-20s: %s\n" "GIT_COMMITHASH" "${GIT_COMMITHASH}"
fi

if [ -f docker-compose.yml ]; then  
  if [ $IGNORE_OVERRIDE == 0 ]; then
    if [ -f docker-compose.override.yml ]; then
      OVERRIDE='-f docker-compose.override.yml'
    fi
  fi
	docker-compose -f docker-compose.yml ${OVERRIDE} "$@"
else
	echo "No docker-compose.yml in current directory!"
	exit 1
fi
