#!/bin/bash

if [ -f docker-compose.yml ]; then
  OVERRIDE=''
  if [ -f docker-compose.override.yml ]; then
    OVERRIDE='-f docker-compose.override.yml'
  fi
	docker-compose -f docker-compose.yml ${OVERRIDE} up -d "$@"
else
	echo "No docker-compose.yml in current directory!"
	exit 1
fi
