#!/bin/bash
USR=0

if [ "$2" != "" ]; then
    USR="$2"
fi

DC=$(docker ps -a --format "{{.Names}}" | grep "$1" | head -1)
#DC="$1"

docker top $DC || docker run -u ${USR} -it $DC /bin/bash
docker top $DC && docker exec -u ${USR} -it $DC /bin/bash
