#!/bin/bash

printf "Docker internal IP:\n\t"
docker inspect -f "{{ .NetworkSettings.IPAddress }}" $1
printf "Port mappings:\n\t"
docker inspect -f '{{range $p, $conf := .NetworkSettings.Ports}} {{if $conf}} {{$p}} -> {{(index $conf 0).HostPort}} {{end}} {{end}}' $1 | sed -E 's,^[ ]*,,'
