#!/bin/bash

function usage {
    echo "USAGE: $(basename $0) container-name"
}

if [ $# -lt 1 ]; then
    usage
fi

PAT="$1"

while read container
do
    docker rm -f $container
    docker image rm -f $container
done < <(docker ps -a --format "{{.Names}}" | grep "$PAT")
